"""empty message

Revision ID: 05ed2ea340c1
Revises: 3d04eb4024bb
Create Date: 2019-10-04 20:30:43.799656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ed2ea340c1'
down_revision = '3d04eb4024bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
